name: generate-snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: phyffsy
          outputs: github-contribution-grid-snake.svg

      - name: Commit snake SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Atualizando snake"
          add: "github-contribution-grid-snake.svg"
